### ISSUE TITLE
insert watermarks over pdfs in real time

### ISSUE THREAD

**Issue by EarthenSky** [CSSS/csss-site-backend#12]
The watermark should be tiled diagonally with the current user's computing id + "This exam can only be viewed by SFU Professors"

The watermark should be rasterized over the image.

The blitting of the watermark shouldn't take more than 1 second for a pdf with 10 pages, else it will feel sluggish.

This should be implemented as a python function and a test page.

**Comment by EarthenSky** [comment]
Additional Requirements:
- The contents of each PDF page should be rasterized as an image. Next (as mentioned above), our watermarks should be rasterized over the image. This means that each page of the PDF should contain a single image, and there is no way to disable the layer with the watermarks. This is so that people can't easily remove our watermarks.
- The images for each PDF page should be reasonably high quality. Since these pdfs are mostly scans, we should expect that each page is just a single image anyways. In this case, we'll want to use the existing image size of the page.
- The density of the watermarks should be configurable, and we can decide on how intrusive we want them to be later. Perhaps after consulting SFU. For starters, let's try something tiled 5x5 or more, like [this](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Fwatermark&psig=AOvVaw10e5mZw3o3mwEhNJ106TlO&ust=1722915662268000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCIi23ZH33IcDFQAAAAAdAAAAABBs)

**Comment by EarthenSky** [comment]
I think the hardest part is going to be dealing with the case where a pdf has a lot of vector elements (like text), that has to be converted into an image. Maybe we can leave this case for later.

**Comment by DerpyWasHere** [comment]
As per our discussion, I've got the entire pipeline returning as binary (BytesIO) the entire way. Note that this _does_ introduce a couple dependencies. Mainly:

- [reportlab](https://pypi.org/project/reportlab/)
- [pymupdf](https://pypi.org/project/PyMuPDF/)
- [pypdf](https://pypi.org/project/pypdf/) 

I'm using a combination of reportlab and pypdf to actually create the dynamic watermark, pypdf to apply the watermark, and pymupdf to rasterize after watermarking. This is to prevent removal as per the additional requirements.

The density of the watermarking is made variable; however, I'd like to tinker/workshop the tiling a bit. Mostly because of the wildly large tiling it generates. I also am likely going to change the watermark text to include a timestamp. Something of the form: `This exam was generated for {computing_id} at {time}`

With respect to quality, the dpi when rasterizing is controlled by a `dpi` variable with default = 300.

**Comment by EarthenSky** [comment]
> Mainly:
> [reportlab](https://pypi.org/project/reportlab/)
> [pymupdf](https://pypi.org/project/PyMuPDF/)
> [pypdf](https://pypi.org/project/pypdf/)

It's a little sucky we need to use 3 libraries, but I'm happy you managed to get it to work at all so quickly! I've used pypdf before and it's nice.
